/***2019-05-02 andy 工具生成*/
import { base64_d3_light_1 } from "./d3/d3_light_1";
import { base64_d3_light_2 } from "./d3/d3_light_2";
import { base64_d3_light_3 } from "./d3/d3_light_3";
import { base64_d3_light_4 } from "./d3/d3_light_4";
import { base64_d3_mat_bossdoor } from "./d3/d3_mat_bossdoor";
import { base64_d3_mat_bossdoorbox } from "./d3/d3_mat_bossdoorbox";
import { base64_d3_mat_ef_o09091 } from "./d3/d3_mat_ef_o09091";
import { base64_d3_mat_ef_s09081 } from "./d3/d3_mat_ef_s09081";
import { base64_d3_roadmat } from "./d3/d3_roadmat";
import { base64_d3_scene } from "./d3/d3_scene";
import { base64_d3_shuzi20 } from "./d3/d3_shuzi20";
import { base64_d3_shuzi25 } from "./d3/d3_shuzi25";
import { base64_d3_shuzi40 } from "./d3/d3_shuzi40";
import { base64_d3_beishu_beishu } from "./d3/d3_beishu_beishu";
import { base64_d3_beishu2_beishu } from "./d3/d3_beishu2_beishu";
import { base64_d3_m_efsphere01_m_efSphere01 } from "./d3/d3_m_efsphere01_m_efSphere01";
import { base64_d3_road_0_road_0 } from "./d3/d3_road_0_road_0";
import { base64_blue2 } from "./blue2";
import { base64_kt727 } from "./kt727";
import { base64_light } from "./light";
import { base64_road_0 } from "./road_0";
import { base64_shu20 } from "./shu20";
import { base64_shu25 } from "./shu25";
import { base64_shu40 } from "./shu40";
import { base64_t_ice } from "./t_ice";
import { base64_t_s09081 } from "./t_s09081";
import { base64_d3_blueEffectMat } from "./d3/d3_blueEffectMat";
import { base64_d3_blueMat } from "./d3/d3_blueMat";
import { base64_d3_mat_bossStage02 } from "./d3/d3_mat_bossStage02";
import { base64_d3_mat_mountain01 } from "./d3/d3_mat_mountain01";
import { base64_d3_redEffectMat } from "./d3/d3_redEffectMat";
import { base64_d3_redMat } from "./d3/d3_redMat";
import { base64_d3_roleblue } from "./d3/d3_roleblue";
import { base64_d3_LittleMan_m_qiutixiaoren } from "./d3/d3_LittleMan_m_qiutixiaoren";
import { base64_d3_m_laya_qiutirenBoxing_boxing } from "./d3/d3_m_laya_qiutirenBoxing_boxing";
import { base64_d3_m_laya_qiutirenIdle_idle } from "./d3/d3_m_laya_qiutirenIdle_idle";
import { base64_d3_m_laya_qiutirenIdle_m_laya_qiutiren } from "./d3/d3_m_laya_qiutirenIdle_m_laya_qiutiren";
import { base64_d3_m_laya_qiutirenPunch_Combo_combo } from "./d3/d3_m_laya_qiutirenPunch_Combo_combo";
import { base64_d3_m_laya_qiutirenRunning_running } from "./d3/d3_m_laya_qiutirenRunning_running";
import { base64_d3_m_bossStage02_m_bossStage02 } from "./d3/d3_m_bossStage02_m_bossStage02";
import { base64_d3_m_bossStageDoor02_doorBox } from "./d3/d3_m_bossStageDoor02_doorBox";
import { base64_d3_m_bossStageDoor02_doorL } from "./d3/d3_m_bossStageDoor02_doorL";
import { base64_d3_m_bossStageDoor02_doorR } from "./d3/d3_m_bossStageDoor02_doorR";
import { base64_d3_m_elementmountain_m_elementmountain } from "./d3/d3_m_elementmountain_m_elementmountain";
import { base64_t_bossStage02 } from "./t_bossStage02";
import { base64_d3_m_laya_mofamen_m_laya_mofamen } from "./d3/d3_m_laya_mofamen_m_laya_mofamen";
import { base64_d3_PlayAble } from "./d3/d3_PlayAble";
import { base64_frame } from "./frame";
import { base64_game } from "./game";
import { base64_loading } from "./loading";
export class CustomBase64{
	constructor(){}
	public static d3_light_1:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/material/light_1.lmat","light_1.lmat",base64_d3_light_1.base64json);
	public static d3_light_2:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/material/light_2.lmat","light_2.lmat",base64_d3_light_2.base64json);
	public static d3_light_3:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/material/light_3.lmat","light_3.lmat",base64_d3_light_3.base64json);
	public static d3_light_4:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/material/light_4.lmat","light_4.lmat",base64_d3_light_4.base64json);
	public static d3_mat_bossdoor:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/material/mat_bossdoor.lmat","mat_bossdoor.lmat",base64_d3_mat_bossdoor.base64json);
	public static d3_mat_bossdoorbox:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/material/mat_bossdoorbox.lmat","mat_bossdoorbox.lmat",base64_d3_mat_bossdoorbox.base64json);
	public static d3_mat_ef_o09091:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/material/mat_ef_o09091.lmat","mat_ef_o09091.lmat",base64_d3_mat_ef_o09091.base64json);
	public static d3_mat_ef_s09081:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/material/mat_ef_s09081.lmat","mat_ef_s09081.lmat",base64_d3_mat_ef_s09081.base64json);
	public static d3_roadmat:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/material/roadmat.lmat","roadmat.lmat",base64_d3_roadmat.base64json);
	public static d3_scene:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/material/scene.lmat","scene.lmat",base64_d3_scene.base64json);
	public static d3_shuzi20:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/material/shuzi20.lmat","shuzi20.lmat",base64_d3_shuzi20.base64json);
	public static d3_shuzi25:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/material/shuzi25.lmat","shuzi25.lmat",base64_d3_shuzi25.base64json);
	public static d3_shuzi40:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/material/shuzi40.lmat","shuzi40.lmat",base64_d3_shuzi40.base64json);
	public static d3_beishu_beishu:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/mesh/beishu-beishu.lm","beishu-beishu.lm",base64_d3_beishu_beishu.base64json);
	public static d3_beishu2_beishu:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/mesh/beishu2-beishu.lm","beishu2-beishu.lm",base64_d3_beishu2_beishu.base64json);
	public static d3_m_efsphere01_m_efSphere01:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/mesh/m_efsphere01-m_efSphere01.lm","m_efsphere01-m_efSphere01.lm",base64_d3_m_efsphere01_m_efSphere01.base64json);
	public static d3_road_0_road_0:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/mesh/object/road_0-road_0.lm","road_0-road_0.lm",base64_d3_road_0_road_0.base64json);
	public static blue2:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/picture/blue2.jpg","","",base64_blue2.base64img);
	public static kt727:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/picture/kt727.jpg","","",base64_kt727.base64img);
	public static light:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/picture/light.png","","",base64_light.base64img);
	public static road_0:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/picture/road_0.jpg","","",base64_road_0.base64img);
	public static shu20:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/picture/shu20.png","","",base64_shu20.base64img);
	public static shu25:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/picture/shu25.png","","",base64_shu25.base64img);
	public static shu40:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/picture/shu40.png","","",base64_shu40.base64img);
	public static t_ice:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/picture/t_ice.jpg","","",base64_t_ice.base64img);
	public static t_s09081:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Art/picture/t_s09081.png","","",base64_t_s09081.base64img);
	public static d3_blueEffectMat:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Material/blueEffectMat.lmat","blueEffectMat.lmat",base64_d3_blueEffectMat.base64json);
	public static d3_blueMat:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Material/blueMat.lmat","blueMat.lmat",base64_d3_blueMat.base64json);
	public static d3_mat_bossStage02:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Material/mat_bossStage02.lmat","mat_bossStage02.lmat",base64_d3_mat_bossStage02.base64json);
	public static d3_mat_mountain01:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Material/mat_mountain01.lmat","mat_mountain01.lmat",base64_d3_mat_mountain01.base64json);
	public static d3_redEffectMat:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Material/redEffectMat.lmat","redEffectMat.lmat",base64_d3_redEffectMat.base64json);
	public static d3_redMat:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Material/redMat.lmat","redMat.lmat",base64_d3_redMat.base64json);
	public static d3_roleblue:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Material/roleblue.lmat","roleblue.lmat",base64_d3_roleblue.base64json);
	public static d3_LittleMan_m_qiutixiaoren:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Model/LittleMan-m_qiutixiaoren.lm","LittleMan-m_qiutixiaoren.lm",base64_d3_LittleMan_m_qiutixiaoren.base64json);
	public static d3_m_laya_qiutirenBoxing_boxing:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Model/model/m_laya_qiutirenBoxing-boxing.lani","m_laya_qiutirenBoxing-boxing.lani",base64_d3_m_laya_qiutirenBoxing_boxing.base64json);
	public static d3_m_laya_qiutirenIdle_idle:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Model/model/m_laya_qiutirenIdle-idle.lani","m_laya_qiutirenIdle-idle.lani",base64_d3_m_laya_qiutirenIdle_idle.base64json);
	public static d3_m_laya_qiutirenIdle_m_laya_qiutiren:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Model/model/m_laya_qiutirenIdle-m_laya_qiutiren.lm","m_laya_qiutirenIdle-m_laya_qiutiren.lm",base64_d3_m_laya_qiutirenIdle_m_laya_qiutiren.base64json);
	public static d3_m_laya_qiutirenPunch_Combo_combo:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Model/model/m_laya_qiutirenPunch Combo-combo.lani","m_laya_qiutirenPunch Combo-combo.lani",base64_d3_m_laya_qiutirenPunch_Combo_combo.base64json);
	public static d3_m_laya_qiutirenRunning_running:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Model/model/m_laya_qiutirenRunning-running.lani","m_laya_qiutirenRunning-running.lani",base64_d3_m_laya_qiutirenRunning_running.base64json);
	public static d3_m_bossStage02_m_bossStage02:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Model/m_bossStage02-m_bossStage02.lm","m_bossStage02-m_bossStage02.lm",base64_d3_m_bossStage02_m_bossStage02.base64json);
	public static d3_m_bossStageDoor02_doorBox:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Model/m_bossStageDoor02-doorBox.lm","m_bossStageDoor02-doorBox.lm",base64_d3_m_bossStageDoor02_doorBox.base64json);
	public static d3_m_bossStageDoor02_doorL:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Model/m_bossStageDoor02-doorL.lm","m_bossStageDoor02-doorL.lm",base64_d3_m_bossStageDoor02_doorL.base64json);
	public static d3_m_bossStageDoor02_doorR:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Model/m_bossStageDoor02-doorR.lm","m_bossStageDoor02-doorR.lm",base64_d3_m_bossStageDoor02_doorR.base64json);
	public static d3_m_elementmountain_m_elementmountain:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Model/m_elementmountain-m_elementmountain.lm","m_elementmountain-m_elementmountain.lm",base64_d3_m_elementmountain_m_elementmountain.base64json);
	public static t_bossStage02:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/Game/Texture/t_bossStage02.jpg","","",base64_t_bossStage02.base64img);
	public static d3_m_laya_mofamen_m_laya_mofamen:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/Assets/profeb/m_laya_mofamen-m_laya_mofamen.lm","m_laya_mofamen-m_laya_mofamen.lm",base64_d3_m_laya_mofamen_m_laya_mofamen.base64json);
	public static d3_PlayAble:Base64Type=new Base64Type(Define.CDN+"/3d/scene/LayaScene_PlayAble/Conventional/PlayAble.ls","PlayAble.ls",base64_d3_PlayAble.base64json);
	public static atlas_frame:Base64Type=new Base64Type("frame.png","",base64_frame.base64json,base64_frame.base64img);
	public static atlas_game:Base64Type=new Base64Type("game.png","",base64_game.base64json,base64_game.base64img);
	public static atlas_loading:Base64Type=new Base64Type("loading.png","",base64_loading.base64json,base64_loading.base64img);

	//预加载，比如3D资源Base64
	public static arrLoad:Array<Base64Type>=[CustomBase64.d3_light_1,CustomBase64.d3_light_2,CustomBase64.d3_light_3,CustomBase64.d3_light_4,CustomBase64.d3_mat_bossdoor,CustomBase64.d3_mat_bossdoorbox,CustomBase64.d3_mat_ef_o09091,CustomBase64.d3_mat_ef_s09081,CustomBase64.d3_roadmat,CustomBase64.d3_scene,CustomBase64.d3_shuzi20,CustomBase64.d3_shuzi25,CustomBase64.d3_shuzi40,CustomBase64.d3_beishu_beishu,CustomBase64.d3_beishu2_beishu,CustomBase64.d3_m_efsphere01_m_efSphere01,CustomBase64.d3_road_0_road_0,CustomBase64.d3_blueEffectMat,CustomBase64.d3_blueMat,CustomBase64.d3_mat_bossStage02,CustomBase64.d3_mat_mountain01,CustomBase64.d3_redEffectMat,CustomBase64.d3_redMat,CustomBase64.d3_roleblue,CustomBase64.d3_LittleMan_m_qiutixiaoren,CustomBase64.d3_m_laya_qiutirenBoxing_boxing,CustomBase64.d3_m_laya_qiutirenIdle_idle,CustomBase64.d3_m_laya_qiutirenIdle_m_laya_qiutiren,CustomBase64.d3_m_laya_qiutirenPunch_Combo_combo,CustomBase64.d3_m_laya_qiutirenRunning_running,CustomBase64.d3_m_bossStage02_m_bossStage02,CustomBase64.d3_m_bossStageDoor02_doorBox,CustomBase64.d3_m_bossStageDoor02_doorL,CustomBase64.d3_m_bossStageDoor02_doorR,CustomBase64.d3_m_elementmountain_m_elementmountain,CustomBase64.d3_m_laya_mofamen_m_laya_mofamen,CustomBase64.d3_PlayAble];
}